apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 7T
  nfs:
    path: /mnt/sdb
    server: 192.168.0.13
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7T
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 30s
  chart:
    spec:
      chart: jellyfin
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  maxHistory: 5
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    persistence:
      config:
        enabled: false
      data:
        enabled: true
        existingClaim: "longhorn-media-pvc"
        subPath: media
        mountPath: /media
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        jellyfin.io/enable: "true"
      hosts:
        - host: &host "jellyfin.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

