apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 7T
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/sdb
    server: 192.168.0.13
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
spec:
  storageClassName: "nfs"
  selector:
    matchLabels:
      type: "media-nfs-pv"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7T
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      data:
        enabled: true
        isPvc: true
        existingClaim: "media-nfs-pvc"
        storageClass: "nfs"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          jellyfin.io/enable: "false"
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
