---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      media:
        enabled: true
        name: qbittorrent-media
        mountPath: /media
      downloads:
        enabled: true
        type: emptyDir
        mountPath: /downloads
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          qbittorrent.io/enable: "false"
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
  #   persistence:
  #     data:
  #       enabled: true
  #       type: emptyDir
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
