
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      shared:
        enabled: true
        type: pvc
        mountPath: /shared
        existingClaim:  qbittorrent-media

        # -- If the `SizeMemoryBackedVolumes` feature gate is enabled, you can
        # specify a size for memory backed volumes.
        sizeLimit:  # 1Gi
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          qbittorrent.io/enable: "false"
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
  #   persistence:
  #     data:
  #       enabled: true
  #       type: emptyDir
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128M
