---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag:
      pullPolicy: IfNotPresent

    settings:
      automaticPortSetup: false

    env:
      TZ: UTC

    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: false
        type: ClusterIP
        ports:
          bittorrent:
            enabled: true
            port: 6881
            protocol: TCP
            targetPort: 6881

    ingress:
      main:
        enabled: false

    persistence:
      config:
        enabled: false

      media:
        enabled: false
        mountPath: /media

      downloads:
        enabled: false
        mountPath: /downloads

    # metrics:
    #   enabled: false
    #   serviceMonitor:
    #     interval: 15s
    #     scrapeTimeout: 5s
    #     labels: {}
    #   prometheusRule:
    #     enabled: false
    #     labels: {}
    #     rules: []
    #   exporter:
    #     image:
    #       repository: esanchezm/prometheus-qbittorrent-exporter
    #       tag: v1.2.0
    #       pullPolicy: IfNotPresent
    #     env:
    #       user: "admin"
    #       password: "adminadmin"
    #       port: 9022
    #       logLevel: INFO


  # values:
  #   ingress:
  #     main:
  #       enabled: true
  #       ingressClassName: internal
  #       annotations:
  #         qbittorrent.io/enable: "false"
  #       hosts:
  #         - host: &host "qbittorrent.${SECRET_DOMAIN}"
  #           paths:
  #             - path: /
  #               pathType: Prefix
  #       tls:
  #         - hosts:
  #             - *host
  #   persistence:
  #     data:
  #       enabled: true
  #       type: emptyDir
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128M
