apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-media-volume
  labels:
    type: local
spec:
  storageClassName: qbittorrent-media
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sdb/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media-claim
spec:
  storageClassName: qbittorrent-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      media:
        # -- Enables or disables the persistence item
        enabled: true

        # -- Sets the persistence type
        # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
        type: pvc

        # -- Where to mount the volume in the main container.
        # Defaults to `/<name_of_the_volume>`,
        # setting to '-' creates the volume but disables the volumeMount.
        mountPath:  # /config
        # -- Specify if the volume should be mounted read-only.
        readOnly: false
        # -- Override the name suffix that is used for this volume.
        nameOverride:

        # -- Storage Class for the config volume.
        # If set to `-`, dynamic provisioning is disabled.
        # If set to something else, the given storageClass is used.
        # If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
        storageClass:  # "-"

        # -- AccessMode for the persistent volume.
        # Make sure to select an access mode that is supported by your storage provider!
        # [[ref]](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
        accessMode: ReadWriteOnce

        # -- The amount of storage that is requested for the persistent volume.
        size: 10Gi

        # -- Set to true to retain the PVC upon `helm uninstall`
        retain: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          qbittorrent.io/enable: "false"
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
  #   persistence:
  #     data:
  #       enabled: true
  #       type: emptyDir
  #   resources:
  #     requests:
  #       cpu: 100m
  #       memory: 128M
