apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-media-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 250Gi
