apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5T
