apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 7T
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: "10Gi"
