apiVersion: batch/v1
kind: Job
metadata:
  namespace: media
  name: migrate-pv-longhorn-media-pvc
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: debian
        resources:
            requests:
                memory: "1Gi"
                cpu: "0.5"
            limits:
                memory: "1Gi"
                cpu: "0.5"
        command: [ "/bin/bash", "-c" ]
        args:
          - apt-get update && apt-get install -y rsync &&
            ls -lah /src_vol /dst_vol &&
            df -h &&
            rsync -avPS --delete /src_vol/ /dst_vol/ &&
            ls -lah /dst_vol/ &&
            du -shxc /src_vol/ /dst_vol/
        volumeMounts:
        - mountPath: /src_vol
          name: src
          readOnly: true
        - mountPath: /dst_vol
          name: dst
      restartPolicy: Never
      volumes:
      - name: src
        persistentVolumeClaim:
          claimName: kube-system/longhorn-media-pvc
      - name: dst
        persistentVolumeClaim:
          claimName: media-pvc
  backoffLimit: 1
