ansible_become_pass: ENC[AES256_GCM,data:tciQwQYj5Vw7,iv:ljamkjkS4U5G1JXqEop1eVKozDl/J9ZzmfO4XQ1sJgI=,tag:Qwws4uv/gKA9g2ExE1yNvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNXcrVlM3NUdCcTY1MTQv
            MGtiNzFLQ0d5bDNseUc0OHNtbEhlcFF3SG40ClQ3Zy8xVHIydkxLenY1dUxJaU1R
            dlpKTjZVdHdoZlNPMDJWZU9Fd1AyWE0KLS0tIGg2RUl2SklIR0tWQkZQNHhvNDBH
            aHhjUkZVZE5TWUFZQlk4cEg4dW9EUncKXC6Ro4A0tG7nNej5cRZoQMSNuve/zoyN
            Oiw+9EiLvxQ7yVGs5M8iAXA468skrEoJESRoVaLdu7LHectikWHZuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T20:50:57Z"
    mac: ENC[AES256_GCM,data:xLaTPlyeucxUjnjoZmoyz4dfTJpjaXksuGTr+zoT7gqTFa4Wn3NamrY6ObY0BVOHVs0NGv5mgLRmNDwDNq8tvA1SvD/2bNfO5D7oXQ/leMyqL4jq23CEtzJy1HShOlgNDZrUIDB0NuLGmOaL1mdUzlZN7OHh+pkmvJzK5DqSGVg=,iv:MBImC0DtDhgh/EjFOegi2lREupSg7QZraouQ7qQFCK8=,tag:YX6kXjiuOwKP01PJ9EKDCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
