ansible_become_pass: ENC[AES256_GCM,data:GVKfibbGqIaT,iv:v3XRy6zIkLVDg7Guh8hS9hKYPdXuK7Jikw22qGD/crc=,tag:QESYU1mP1QgYrVP4M4vFqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWGk2TjNKTEZnNDAxZGg4
            YzNVKzdadEVVbDFvV3VodXgzOVMzSllvYW5ZClpmTm8zUVNkdWltdVV3NE5BWExk
            NnZtbGozWWlGcXU3TFNXamVreFNWOWsKLS0tIEo4Z3FVV3lyNCs1aGdhK0s3OEJU
            ejB0Q3pzeVNNb0hvWGU1bzQ5aDNaUlEKAgPIFzEuxaRqB3JbSsUoIx7IvbGOU5nm
            kTK3ysRMNyn5FciZaT0aZRfbRFO2pQ3FSWmzGQmgV+cUFF0j5YunKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T03:51:56Z"
    mac: ENC[AES256_GCM,data:5GUkLRJ0huR+Favq783jC6NrX1XPi1BOTY5HiUiB08ijp25Hfc8cvj8jcN3vPmUjg3xseuJ94xjLtwSYYES3whxp9OopnmI4OBPRTKPFkJjwzyomPRiLhj0SjVYtyq5QTIkHRBtI4vImUsRU5SiBfdhEaU99Z+MPMretD99Hg34=,iv:WA8zXNilXAdM/KvteFb4y+Ea8Z8XNix1w+byvw7vil8=,tag:GMl9MYm/6Nywm7eDf5adNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
