ansible_become_pass: ENC[AES256_GCM,data:Kmhdb1tdc9E+,iv:2SjLo4MmF9v7z5e4bY1r0Hpo8vmiM3FhrD6ceSYWKds=,tag:0UIL3lcvRP2qPm98SA/X/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeTNHaW5tQTBDYmw5QzJ4
            UjExNGtwRTFTZllaRnFWSnZ3aTRGYWRad2dJCmpFanFPSG5USS8vcU9YR2MyT2J4
            UVJLT3VrVTJtd0MvdXhsdkVZb1hHcjgKLS0tIEVTc2dTRm5iQk53ZklxeERQY1Fl
            NHcxa2pWODFaS0w4dUtiKytBN2dJbTAKMn0x32s9CJzW2lxhGrYAdPyok8/Ocglv
            nx4NiXq8wz9vVlX7z31HLaCD8jOTyhPMuzgSDmCRXx81gPiTDzOi8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T02:00:30Z"
    mac: ENC[AES256_GCM,data:PW2eR5MINaGcrM0yGVS6NArnkQUZ4dAK6Y3ryax75b1oFcJZCBmoejs2uY/ppxJQRXonUGpVlrf8rgK4TL/l7WbXfCu5fcnEbug9yiD6xK5awShilGylysDF3OccFDreqEMwVwNXZAWH5dvFlGyUovLLnaOhfaagN+4loYf/Blk=,iv:m8RsRVWobclgF3uEHz+cVLb2Qi4SPb8Mci4YXorq7v8=,tag:PwyPwgihxAcWAt6bgl7xXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
