ansible_become_pass: ENC[AES256_GCM,data:+J1ID++Xj2cl,iv:Jevyqp/adYlB7ydANLGNof7gHAOTeQ8X5mA5o1aDlPg=,tag:J01DbeAXdpl5IfgfWbRNfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRXg3WTdLd1IzaDhFV0gr
            WmM2WmV3SldwS2o2Yy8zRUM1QkQwMXdSNjAwCjVrQnFvZG1UUER1Smd3MXBoNStn
            cWhZQVUxNDhlYnVOSURMTkRjMUNOZzgKLS0tIFU1c1NLUEdHSlkwOGtCVUxQSFNB
            QUh6VHQ2dHIySUxUaGV1SmhoMHFSbTQKuViU4NqygB83CuC2exi0p0vYfqk830Nu
            tt0e9JeHvNzc/pfr0i0lr8hxmV1WgK/4PxjT+tsmZldG/KRjmQBnqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T01:51:54Z"
    mac: ENC[AES256_GCM,data:tnjFvBfgCikshLEOjixycWplrVuB8jZUpj9IDFOcjBa+4xStiKGYcRLSsf7p7VsHvIVsDewkXrT+PsvL4jPCM8d0MAHRmdeoPm5QLc+2R+HF+R/153Tr6DSHJngPDFb+F4wSjEzY5yV8OzHFHixGQBi/wQ4gGtDYxytpcJHiSm4=,iv:8dwlcLu1MAKiApI+HznZEHSpEvc5L+tCRSuHSeb3N5U=,tag:KcChwO704FHxt7SQDLhN0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
