ansible_become_pass: ENC[AES256_GCM,data:lQ/wFVKZQcRy,iv:36LKQlVxZmqqI4nQIDJoArBVkjogt+x80jBiuESYV9M=,tag:zEdk0ZOrWx+P7V2XMBUM2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR0h6NHE4ekNqZzNIVm0x
            KzhiaG5xQnVDdXdNUXNtNXIyZEIvTTlTaWl3CmtGRVhUWG10MGVOMklEWDlaT1cz
            ME5yZDhwUVBydVJ3SEpKNHpTMVRYbEEKLS0tIGIvTHdKNGdnU01Da2luM3VvZVBE
            Q2JuYkR5emprNUxKS0NTMHRlakRTYVUKpGFjEEjek7+5Q+WfIaiZNMQn6dwBXQNQ
            xvqLfpRAt7mvs4G4s4Hsp8rNAj6jDimP6DX37FdzvxZ0NpdrEf556w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T19:43:53Z"
    mac: ENC[AES256_GCM,data:5gnP3xd0veL1+snEEfYrnzm/xL82nHL6sxmJY60C94BdtYHCyrxwwGFaFGSXpUaUsI8KdAW66u1hnNq0y2okfROZ51384+DPa7KWuHuDk3cDK4C+A8coSVfDsv20ro8or0Oo47Ulg1LZMxJmkB53O1J4jwzwolRJhUibpMGheLI=,iv:wJgDccAEAcHc/t5+67MFn0FXEspXw4ag5L5LrnMdBjI=,tag:xtT5AkAK5cUQCqw8tOjaCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
