ansible_become_pass: ENC[AES256_GCM,data:0uC3b3HTATrP,iv:k2Wg/QGUqGy44Fo28mlkxW5gcwjQzVlMhWrd8J5RnbU=,tag:gMFG7VuQu0JqBwaUAbuJ7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMHJ2UUlTZlFsZDMwclFZ
            OTF5YllTanZkaWtDUGZjQ005ajV4a25jR3hJClR5TmE5YXNpSU8vRW95YWtnMzhX
            bjdwb2JRS2Z0ckxTTDRFb1pMdDZ4Z28KLS0tIFlUS003eURBRkpESklMcjhRL1Bk
            eVNrZUxLdDQwbVc0NGdTK1dKbVgxNjAK9oSS3yxbFuXUtJ7jdLT5+kroN4Ayr94v
            NOB3yWf2TPif2XI3x2wGOZa5eNrHUN8KRRzS6kosUDveYOR48kSxWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T03:28:25Z"
    mac: ENC[AES256_GCM,data:tbYYHfYy/d3llrBCauqiSa5aU8k55ryPnRrhdbwPWdVznCJqnlk+0oMo995Z8gjG4CMI/JMT1RZ4WMZ/KdZQhWD2/xovo3FJ7KLFmuxNL6g+ri5Y/AW2P5mA7Uawa60AAlSIPAIrHF++7dplmFsc4/18gdHhRF+BmmlcqJUbQaU=,iv:7qJHcrasQ/gnxh3nat5d+AhW75P4SYtUyR9D34rkIVQ=,tag:vMkrVvpaLrkCQ97npTxJfA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
