ansible_become_pass: ENC[AES256_GCM,data:8lNJd6NRsoga,iv:ECbQaU8EtTFDE2krEzZT5ZT8PZPalvjai6cOpYi9VXs=,tag:YTC1sewxxI28vyWNM5h3sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR3BWNlVVWmpIZnduZEdQ
            dUM5TmhsTTI0SHJVMkZYS1NWam4rNjBGYVJNCnhrOHZIOEtSSTBHR00xUTJMWGZt
            Ukk3TTFuejVobG5YZmNBR1h4K3R3UGcKLS0tIEVuOWUxdEt1RzNpZUMvQmQwNG9i
            Q3NoQnFKNmpKbUxNa0ZRT0h1Uzc2U2cKDoEhaOiW/2nJXw8Zw8QjGKcyO3aWEtYL
            7y/tjmOnVUVl1X6AK48fsQnPkasw9vqXs76xHHsdsFo0CZjH2aEIew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T22:47:54Z"
    mac: ENC[AES256_GCM,data:t6Gk9/OHwdzY16MtbLuOS3lEiFX4KITZmEaa4NWaxyLxPY+sVnEpb04RbnH1K5eXWlIhRYgdIyXR9vrDUsw+ohk1NWd5PPxuoZsnaDIeWN/FV//iKiezvsowJc2NjRgpbmg/DypjOxtNF05vO+EkoL5arzPxKRZCpQwJ14ZlcQI=,iv:kCBrJF/ZqruBlHUBVZSZe9FbIXChG6jponq/1mTBZYw=,tag:nB8O14b/aDsEhnsN4YI98w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
