ansible_become_pass: ENC[AES256_GCM,data:zudV04LF/D2t,iv:38q66tGHn9qQgntHVJAo/mzgQzcbv18Ja2VY29uEBw0=,tag:dcXwVV/aLlJKMvvUF4wToQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRM2RNUTZJZlc5U2o2am41
            T0pqYi80S3ErUEtSY3BzQ0RZemRXZ1RkKzFVCjJ2QzhDa1ovb2xMUXNuOUVTeDFD
            SGVlM0tXNVAwSFg3QXFRcW9PZWxXMVEKLS0tIDhoMURmcTR5cUV5MWJESFFDenFN
            bmpWUWM2LzI2OEw2WDZDOVZyY2hVYUUKzXTUPAAkqjSssWFE6fUG+4n6czgiL73a
            sIk9kv2IuyrbcO7h4xBlmDwT5fIm4FLgWeoiN9maXcFSHGzY3l4soA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T17:37:16Z"
    mac: ENC[AES256_GCM,data:05EIzbUcfBYrKB8V7qI934v1beAlLWoTDkmZpc7yGPPEVk45hBDYfeFWzpn6Ej+Imq5p5ck6gd62NCAtEGHWCe+WoUlbkwPYS2UpBELyJS2r9mkLbOSQywMy4O2EdRB/9fUeHDiVK3OXQkRf2oBlpFeMGLlEQSjrjAqL/LGMJr4=,iv:pp6GZHFpz0rPGjhY0vWEUBBOy9OXvzw2d2zrj3LsD2Y=,tag:IcOBmjED1ktD+N19cQXQ7Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
