ansible_become_pass: ENC[AES256_GCM,data:rZte39B5yfQX,iv:sbgOqNGaZghtc486sqBlAm+Cs0aU+5ZQMrLbCr+C+Hs=,tag:pGiiMcdC38mwHYboGxTluQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Yi9pdEV0UFJnWTdKMHJD
            YWs4TFd2STZHR3BZd01LOVNCSXZVUFg3REZZCllMZC85dFVoeXEwVzNITDU0cFg2
            anlKVGRkZDA2VzN0QmxrbXRxbzI2dDQKLS0tIDQvaXVnRWkzRmJYSTdSZXRoKzk0
            NGpaM3o2REV2ZXZtTVR2US9ISURHa0EKyPb1NHNqHimlhwp3pQqFCJwWTpQG8/PD
            NaQZ6SSrOFKX1IGcX2qo4enSbHg1tYIUkPO76oMtZBrTZDIGNZ04uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T02:48:45Z"
    mac: ENC[AES256_GCM,data:EqyqspHBm2e78aVKZtNdGtFGXU1CXMlJC4FJQrFg+/3lmTProx+3/FV/L8ltJxUuVgFwFDDHiJuGb9rgyCIyPvammoCISB+80twWQ7BKvsH6IehlsciVW0XlH4/VkrhW+ECO/dqGwoFPJX+fXKZmGId7qkLLH6onIzmUTy9qMk0=,iv:TdAkngH4yZ05BENuP3gqiaE/DawpIBk4hw4B5KBZiyM=,tag:tCjGIlRp4BGGIa24WeRiaw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
