ansible_become_pass: ENC[AES256_GCM,data:ZO5LFv9I4Jly,iv:XPrpzAsc1IN+8aXzeLtGdYU1STzEBjgrH+VjbWUojrc=,tag:F2d9NA32J2KSriEm9+aCKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbW5IWHk0cGJWeGg0NHpR
            TnNOWGlvb2dNRkM0cy8vWkU4cklDYUVxZHh3Cll6ZWtMV3kyL1hhbmQydGhub1Ix
            dDI2VlVtb2tzYkRLMWhJMW0xVHJUMGcKLS0tIC8wUUJRVXlPMVhZQzRZeGtFNTZR
            ZE5USk5UeWJ5ckdEdXltaXpvR25BNHcK7iLoqfrAfivV9X3BPagG3bz7mqacsTf9
            bMtKVYYW0+OfzgTntG1RjipLsDf2wQ7b0t957hh4FfP5ktoKGiDSSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T22:39:57Z"
    mac: ENC[AES256_GCM,data:kH1rARZ+p23L4FbLaXN4EOgptPxDjRTlUAiXYT/GvVPEZZJGEd0DC2yqkYGA3iuW3w6PDg/K+Gal4BtXHEdGZrJWAsJe/iH6QZxm9qFd56NHsdTr1nWE5NsEl79RginYeYjLxpH8siBZOCuguTs1DCj5tf+ywcfsCAFq9xkjdZc=,iv:aR36qD1f3XuvRHrPpMUbAXT4ROXdG4mpXi4hJOWa+7c=,tag:e5Xn9mstHfIyxzrS56gjtw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
