apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autobrr
  namespace: media
spec:
  interval: 30s
  chart:
    spec:
      chart: autobrr
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: autobrr
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: kube-system
  values:
    persistence:
      downloads:
        enabled: false
        existingClaim: autobrr-downloads-pvc
        retain: true
      config:
        enabled: true
        existingClaim: autobrr-config-pvc
        retain: true
      media:
        enabled: true
        retain: true
        existingClaim: media-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          autobrr.io/enable: "true"
        hosts:
          - host: &host "autobrr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
