apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:rOjFxhQkhe7P,iv:im1sp0QtkwDblC0u0DB7fmiiMc1V8P4cJGioeX2x5OI=,tag:Eo+1kn/I47FUpvE6411boA==,type:str]
    admin-user: ENC[AES256_GCM,data:w6U7yXU=,iv:klem+Rbz+/HYUfnZID/Crn88vZdOjGAMjKobzIS0HQs=,tag:skF5AEBcQPDRJ8W/uWquRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZUZLTVZqbUNiWUFSaVVG
            T1dxWUpnS3VHeWJaTTV2RWdKb1hzU2Q4QW5JCk9wdG9JVmZFdDVTYlgzVjg1YUxi
            RVYyNkdJb21lM2UvNC9YZ1cwblZadjgKLS0tIFk0QU1kYUwwTUxvVjk0WHg3dmZv
            ZHZZMWY2Z0tnTllYWldXb1JTUEpReE0KZ7VRl7XHJy30pBy/a5TVrK+JrXeRE7ez
            /CzseF5El9yOT2DzW12vGgoZwWeriQeQb2djPk5gsHpsaYs3GnnF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T19:44:26Z"
    mac: ENC[AES256_GCM,data:yZW0HHIDm5G8xwwkCymj8waouFfJVSJIyjagVVnQtUvvzTqlIE0ZMpK3hg9NinIka96MNFDqgr5fonAx7gO4IFK8T4m3thcephsPnsOda8Sym7zg6F/9uCxcmZxHhQW9jxWBKtAnzJ93EcANyvC1BYdqXyitdCEfG3XTDg6TEGc=,iv:wt/f8+xfnEVn7ZsXRh9QFgazJcgRHcPAKYh2Pf4WHWo=,tag:zj8zcU3bFQbtyKjXnj9AUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
