apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:lDvaO912R9ne,iv:qGX/z2s6s6GrbSnGOuYfziuC20cxXPVNsRlRuqMdbEQ=,tag:/u3FOkpSr0aV4oZO8y7FeQ==,type:str]
    admin-user: ENC[AES256_GCM,data:PgnJml8=,iv:GnS9I/uf0DU+ZS6AsrV/GAJIZ8am0c/pjWuhETDvf38=,tag:QYiSKVUGeGLFai2s30cN/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsenJFd1ZiaVhPMk5iZTNH
            WVNtWXdlT1RXRlhkc1hwMkIzT0FIZEV3TUNVCitDYUdQY3B0YjYxMmRTTElnbWVJ
            TXZQZEdkTUQzOXVZL2ZHUzZwUytwSk0KLS0tIEtvbU1LSlpCMjZFQ2JuYjU3Zncz
            eXI5Nkp1R0FmVlVrcC8zWnpjNUlQRUEKcNw1HxyFSkjac5zGbRCDI6TdAhFsmdw4
            A3aySLxZJASad3Z+z9vi17W1X9Q2F2xw54Pvds092EbPOJIA9a6mcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T22:40:28Z"
    mac: ENC[AES256_GCM,data:qrA27kZvFLgTC6C+bW8FxXeB6R5ZEFLTsCWew2LJRx7SGmYaGaBII0Er2csCtz9bdZYTu9gk8MvWc/bU+OwBcSajWzc44whhCK9WyQHVktDrpZZVKXfN3sSZTtpj9jrLlVLdNkN9jO4z+dhfSfOcaF/T0NH+6x7acajzNDDwMiE=,iv:3iftZiLCKI1Pb+u4l8BCLaawDKVxxNGvhVs0a+Q2KNc=,tag:zlvQHDUqBwJV8ofwWMBg3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
