apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:x1sa0FLuRMC9,iv:CLK4YeGmNW6s/C3DYdvTA/jPn4o96Qn5DeNJY0GN6W4=,tag:LozWOMhNemNwZtJk97YuAw==,type:str]
    admin-user: ENC[AES256_GCM,data:+d/YRjQ=,iv:phYRdjLC0PXSjwLyzwZanqqTJCJYxiMz6+5iBkCSnic=,tag:lPcXk1q8CYb2mYfy4ZpkCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR1Q0bGJ4ZzhJY0tkVGJP
            RTVpV0xYdmNpalZkMWVaRDExcmMrOFVqMG5VCll6NkpVbDh2WkN6TzlxMHhhNDBt
            bWoxS3ZpKzBCdFV2MTB1djQ3Z20xVmcKLS0tIDdZRW4ySTBUOGZES0xqcXZWRGsw
            OXgxeGo4TFkwSDd3ODNXNEFuSHBsdk0KWhAe+Xat+dguYagwVyxAOZ3txK0uG5lt
            cqGmfGSYwKupYB0Fw0tC+xh5njW5FTJ4kHNPtam2ADKcpxv4mJdYUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T22:48:25Z"
    mac: ENC[AES256_GCM,data:uUBjBd1PhfAPAVbTZDmSgPYz5N0m15oqW7Diu+yZuqYkzj22qH0HU+Te0QhIOfh84sbQWPNuV6pJjZVhGw/kgxbkvt1/eHTPTtO4xa0EULxTwzf0Xz/2uVGSTZH7BmjAWML+aptuHCGDmwJe8QBnOm+CMxJSWs8fHanikvSbQgk=,iv:gQLRjw57HguDiN+prBBzor54QkPkGO9AkfU+Em7PsN0=,tag:yDKjY72er8BcVSYHlxa88Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
