apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYkJoK08vWFZ0clRBQWJt
            cnJZcHU5bDk2TjVhT0RqK3RocTVvK1Y4aDNnCnhlSlcreDVtaFJ2cXh3Mjc4K29Q
            QWNENFdVaklGMEFjMFJGQ3ZPT3JqMVEKLS0tIFUyREFta0UyVUhLV0FTOGswZEpU
            VDUzUDhpS0s0QWM0eTlGWGZsV2ZWQmMKBYH5P2Mq3N+h0UVFvp2lPFQ7sE3x0MtS
            Y191GHj5l8gRq8KcMXiap0PXHH8o9sbuFdOw6wxyyWBU9i9eJnddJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T19:44:20Z"
    mac: ENC[AES256_GCM,data:VS22O+kbaTKIvjOjmannierzBLNGvACbQrZcTVUd00Qs4VUnaTJ8p+MgTYIGCqfjV1RV9aJsbx9P0kQC7tiyIKOtz2sUB/WAfc/KStyH+gspg+2mWQQPKf717F75HCl6qrmsJnKPf5m26Yp3x9j83drAya4ULgxmAVPP40emRPU=,iv:RN0DsuspV01BUhfwitSqY//fBOpAiel1yUP50Qx8dR4=,tag:RXtcx8uIMutVawO6TLzw7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
