apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcXZoR0JPZ3ZBUGtkaDE3
            enRONnh5b0x4TFp2THdrdEl0L1lPR3F4cnk0Ck50RFdseWtnNWlvUHZWbUNRUm8y
            UDhJMTdOZ056Z3BTT0MvNms3cS85dzAKLS0tIEZEQnZTd2RxMnZYZ0xSYTBZTHpt
            UUVoK3dQd21aU0ZJN2hHUDhqbnY3ZGMKV0iW0+tBv2qfEj6tzD8+YM51NoWZhIMp
            HAt5a9myEV1u9J1k9L/JPq6RQS4fbFV/da4lnIoSgN86NGjiTd3oyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T20:21:07Z"
    mac: ENC[AES256_GCM,data:0m1gWrPPvSo0j1ZwCFzt3j2PdoFowd3HHqPfCmAg+b0mznMAP7xHAL7AKyCTVVPty90TPGhvHmRnwyz8TEeVYIMQ0iGnAYt/8JVB/zYQ0GiXB/hX912vPerm+76GmcSsS5+xtNWKPgVxcfYc1aIx+PaHujd5WwMOa2lCF9vkpcE=,iv:cyfo04cpiH4frU5nZb6sFtqwik797w8b9loaZ7d+Vao=,tag:CTCgCARjlsHjTJf+9omSHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
