apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSVY4WTU5NUhFQU9POE5j
            MTZHa1ZEeU9pejFOdWNnTmdRRkRKSHgxZ0JNCmN6QmR1UXcxNnVoN0wzN3pSbW5R
            QzF6a1JWTEs3aVN3ZFh2Y0tHVXZUYnMKLS0tIGxtZ1loRjBsNU85OGhkaXQ0em5t
            TzlJMDZVTktXODhqZFpRVEF2WmZJLzAKtFvvxZtbXAxwNs1DoCNjnfkXiQ+gvLc1
            /xWuRAp8SXsgyBgmFQuJ/Hqq4f88YZ9p0SRs2oEJ4kPAMsjcR7NoIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T03:08:04Z"
    mac: ENC[AES256_GCM,data:j+ja0wJxiLkpx6uKlanQSl9sCyg81tDqUS8PBaF8vVmyfaGHHjEwwZxkdDv9+XqEQzkJE4pehjc6DfeVJPFGCZPwXmcR2vn40LmC3s9VJ3Z+a94kiYibi5h9YwUwWcnAxpEXg9/pbzsSIFsCOyeFmCT3h1sW1fLzfGY4ymL3e74=,iv:JhXIeGgUOsJhSDZiiO67UPsO1UO1h85unvWXshHDGZs=,tag:LeaqIn2XGgc90omakFf09g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
