apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30s
  chart:
    spec:
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: qbittorrent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: kube-system
  values:
    persistence:
      config:
        enabled: true
        skipUninstall: true
        existingClaim: qbittorrent-config-pvc
      media:
        enabled: true
        skipUninstall: true
        existingClaim: media-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          qbittorrent.io/enable: "true"
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
