---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorent
  namespace: default
spec:
  dependsOn:
    - name: longhorn
      namespace: default
  interval: 30m
  chart:
    spec:
      chart: qbittorent
      version: 4.5.4
      sourceRef:
        kind: HelmRepository
        name: qbittorent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "qbittorent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      # -- Default persistence for configuration files.
      # @default -- See below
      config:
        # -- Enables or disables the persistence item
        enabled: true

        # -- Sets the persistence type
        # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
        type: pvc

        # -- Storage Class for the config volume.
        # If set to `-`, dynamic provisioning is disabled.
        # If set to something else, the given storageClass is used.
        # If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
        storageClass:  longhorn # "-"

        # -- If you want to reuse an existing claim, the name of the existing PVC can be passed here.
        existingClaim:  media-pvc # your-claim

        # -- Used in conjunction with `existingClaim`. Specifies a sub-path inside the referenced volume instead of its root
        # subPath:  # some-subpath

        # -- AccessMode for the persistent volume.
        # Make sure to select an access mode that is supported by your storage provider!
        # [[ref]](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
        # accessMode: ReadWriteOnce

        # -- The amount of storage that is requested for the persistent volume.
        size: 20Gi

        # -- Set to true to retain the PVC upon `helm uninstall`
        retain: true

      # # -- Create an emptyDir volume to share between all containers
      # # [[ref]]https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
      # # @default -- See below
      # shared:
      #   enabled: false
      #   type: emptyDir
      #   mountPath: /shared

      #   # -- Set the medium to "Memory" to mount a tmpfs (RAM-backed filesystem) instead
      #   # of the storage medium that backs the node.
      #   medium:  # Memory

      #   # -- If the `SizeMemoryBackedVolumes` feature gate is enabled, you can
      #   # specify a size for memory backed volumes.
      #   sizeLimit:  20Gi
    resources:
      requests:
        cpu: 100m
        memory: 128M
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: media-pvc
  namespace: default
spec:
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
