apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:vjDjBr4JnseDowXOb1sNoYq3Dg7bOFWk/Mqoe85n8UDwSroXygNofg==,iv:s06GenkWHfuGrn+BtcPpYgZf301pfmmZhT5WUAim3qk=,tag:XupCJ8qVSD+1xa0AhD9lpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSFFsVjlDK1paZ2RoT254
            RkcxUTRPN3hLRjMyeEQyMU1MVmVKa2VOVERFCjdqUERxSDAxQ3loRGE5WTZuME9j
            cVhhZ3ZYVGczdFNwM3dsRFNzUzBldnMKLS0tIFhkcnpGSTZhSjcydEVSSlhPWW05
            cFFDRVd3NDRpRGo5LzRxbmFSTW1JR0EK4WI4EhAqoAYypPuNdsrDueP9IrlH7N0x
            ILt94yGZiNpUi+M+re50GqcsnrZzjJmIrpsw0jXScf+34Uf2xG/Arw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T01:58:16Z"
    mac: ENC[AES256_GCM,data:Vk1sLhoEVRiR4VCyvBFas78kTmJcZnkQI7sKzoymvFbxJ6xx/U6LsZJA9rGotSLoGcNSLdYhcmxVGKU8CgydszKEsZSl5KmFVbJJWqRMzlOa8CaG6Xt2h6Achr/d8O2/vnnsmzVTPBJdsjDML3E9HCr/jQOLautc6wyFtsqmxYg=,iv:FkKgs3Rm2cAzyKgoiZNrTSdzafZ7qFZCEY6CDOXGdxo=,tag:nI3I93dCYbNcZnHHtShs5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
