apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:5Ct56ryLr514aBIN582Lhw9vIO+aQA8M88kc4TRIxtjbvFQAP1xReA==,iv:tBL/B9HeAFRgaPb30LBZRhKQ/MjFONEcrh+JLnwnCiw=,tag:zPKVoVjLA0bwXUpEzs2jEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdTZuK3d6Yk9wU2FQeHNL
            TW1LZi9xNCtWSE43ckFDczBHM1hTOTROa0gwCmh0RHdwSWNLMkIrQms1bnZEazhj
            KzRVOCtXWFljWWFHV2N6VHIwMCs1ZVkKLS0tIDJRdE0vd0EyVGlsVkY2WWorcUFi
            NUlrWU1KVHBDVHQ4VGdsSFkwTy92NFkKQQ/jv+33ORUDc1ulsbH+09BF35Yzr+FK
            D+j5JKq1AGeAf5KAQ0ocpcOhNWymGfFrG7zIgrzDloXDzCqrN+rdMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T22:40:24Z"
    mac: ENC[AES256_GCM,data:weNpBoS0M6yVg+ifwhkjMBveRKkKGNWhWBD1RGsg3/eJgNFCxZac2d1tRRNvo4Nz283gECeiWcxpDAVD22yCkZCaXHX40zYXm3lmgCNjF4SnyqdcWRRegHbFUOWbPKfv7C2BgtyRXkv7O64WRLRmYOH3/Yg7zh7YB62vZ+nFgRU=,iv:z7TwMjCPSQAizXEctunNPhC2oXxCfiwROpe56RdEEcw=,tag:dizhMlQ++bPLvzKJwwOSmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
