apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Fxk5U2qRaL5I1UPdB0bD3VU9w5CFGtVcwLEV1seQAg4XgegSiRT4ww==,iv:GByyRMTLDGpo3wNcBeof/at11oSlq/8W6a6kM17sYes=,tag:picp37Vax+i+Ub0UMKtFZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTGVTR0o1a2xMSUdvWEhM
            U2FTNlJRaW5zOGtJeTRLbUFTRDhRT2luQzJnCkZIMm1OazRxTFF2L0hyUWQyTTBu
            WE1GbTkvZGZkQk1EYk9TNklDb2syYUkKLS0tIDQ2MTJRWWhhYk5Ya2FybHhubWhB
            MEc2ZUMrSExobk5seXkyMWpjRGVKb2MKxQzj3I97Rzr/O/oq+HMQtw+8BtpOOeTd
            e1aSIHJSNUMvi9BWpx2v57CKbGGcnG9CDF31MCLk14oDgvfn/YzSAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T01:52:20Z"
    mac: ENC[AES256_GCM,data:hE+MtjJQnxhVI9o/+0LTQC4eTlSF0MSKEmlhobv10mizFEdXM74KycTh7perk4WvkjgXw2uTpnl7A8Mw9NgpgN3/de2/PtoXizcqQ1nOYimg0yis+2WrME/iGXz5mmlbFTYDByFa0RJhw8hMZgEdfaOsBma405vZIq7Vo8RDZgc=,iv:MN3fYcQqKMYIdoPPQ1290tAPEMkxXizyI0+mIQ7EuMI=,tag:8Fm674mSRMe6fLqq96+SSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
