apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:wuBka1rQqEkOspXcmTpiOt3JHDJNFe6bRioDQccHFv2gX+ifU0s/2A==,iv:KfQ0DW8YCxmfE4l/UZ6Tb7aReL1PMYUl6V3xyKYQgy4=,tag:636qGbalCjyTkuraKQ4J+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRUZ6STIvMFo4VjM4Kzdt
            aXgrMkxIQ201QTVqZk1WM1RKYUFYNERXbFNRCm5qcG1JenRXRTcwT05FcklrbEIx
            OFUvK3ZXT2tMSUhIZUV6Zlk3UktmVGcKLS0tIE80NEVGZCs2TTBnblVGY0dYZGxK
            Q3JGR3ZvSFRCbHNNcEhxditjWEUwZU0KjDqYd1/HYMJ/erAw7xJpdtIXC0K5M1aO
            6lYlVKbitshm2Euqz72PRPVESUeUZfpUmoEfZ3WbWNxDqTk5niCKIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T01:15:54Z"
    mac: ENC[AES256_GCM,data:XbQhkpCzDCSMoYjiKIttpQPgdOhDJ70LQdHmJHxIzlC/PTTl9ylbEfvGFSnqvPdxf+B+H0S13BkukCkGV2Hku0HFEUOeZLwWkFUwgC+EgAZ1BTX4YFrc0i48E2rhLq6a+pWfYuNDUo6SjDRJ/cUMqWJLl3iVxkqsD1P+DIZf3N8=,iv:vrh2HDZFD44Qgwtsz9x4W7wYKBhI2cSx7MkZrqU7a8g=,tag:KUfu+2itcjPCDZv/LXLXhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
