apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:hBxorhLPC0FcAiNK2hN00Ac2C+qm4w4LQ4WruuRecdWupcsVnOYSpQ==,iv:bfmV3sqqxBgCYms/5w4CUKNDrC+ph5YDkeqXwugP3kA=,tag:zFpN/0jIiepL+6ERKaDd0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS0V4Rld4amRkNVNRVWJ5
            ZXpPU0E2WFJpazRIU0lOYnRUZE9qQ1lYamtJCnNhcldUWmNxRVgvdjZQUjUybHl2
            QWFURzVwbEYxMXZRdkFaa3ZNUFd4TU0KLS0tIEIwY1Z4ZlMvMlFiY3VqR2xXUDdW
            MEx2aE9kM1o4N2U1dVkxTjRxMkp3OW8KiTyN0hwYRJzAaYGwOqvkD3X1lgPlSuVA
            CzVFPlqCOl9RF3U7WKr7qfjzw7OOB2AdYI67tSXoTcbMk9xBYFFfjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T02:00:59Z"
    mac: ENC[AES256_GCM,data:ANRqwlbVAn8ez/+Xw0bcY9jIgimjt+xAS5FTFhdKfaUzUZkopPi6ha2zU38wZum1I2NFuowGIRbT7F1SqiLsaVBIcRc4eTpfQsyt/2KdXO3OyZKDAMF2Qx+er5KtX00kWJrko7Vf3XeTiQ6kXQR2wDJV6b+i5pHuQI0jy4ePxf8=,iv:KRP1jMK/I54gv0kWW/0iogMNK9cjmUuXuqFNg4RiNNo=,tag:V26sZ8+H/iOYE8R1NXuEqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
