apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:G2DD+q3ABuv3AgCj+YE8XHsiRIQBjayOSvkTZLG/ZlXL7wyTAg+4xg==,iv:wE2hnNSjRlBYPNJH3t0G6352NO4AVppC3WZlRSCWg9Y=,tag:sDfNzEYlMnw9sua/lpkkKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWUxOSEpGN2xDNVhnY0tm
            YnN1MXJqRWRmRmVDbDhlWmxYaldLWEt0UmxvCmsraDFLRHhLZFpNbG5VdTl4NWlV
            WnNMV2NmVzlSZVJ1SmZReCtTZi8yLzAKLS0tIHV4bkdPOFdCVFBkbVRsbVRBejQ1
            WGtRb1JlRklsam0rMGFNay9RUU9neXcKuhszeO7iMtsxLVUUgxukZ3nQpflWBKoA
            +wZGttG8R4PDsFqJ9Zk7f6Ia3lOoobImI8jqQBF+aI24AR8eK9VbAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T00:24:29Z"
    mac: ENC[AES256_GCM,data:0XCt5fMZUkXNK/kIa1LU55UlfjuAAVl4S4px1ZlZWWb95T51CS9ofgr0WuKGrWRP63R/eDTYMewA8JNg2+O2KDRAW1i5AMd/NnwayIUjfl5lI48scpTfjVxBhJQ0cbWwqRXnFXggV2XbFSTv178UGrAph3ImFDedI/9CGCqVMk0=,iv:F9LIYgPcLKW43gG+mpyCET40VNenGAevfuwCvWMKqEc=,tag:xC/T8PD6uOolD0hqf/05WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
