apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:2DviKhBLx10F1rE2spmiiWkF80mL7VU6NpSk61F0skTILLMRI8eGgA==,iv:n7MfWxt+P+2BjAsRIXUBxmI0A0IvzlUaFz8OgjYYDEc=,tag:e0gUObLECx6NN7IR3OwD0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaVpscFVqeS9mZnUxUExH
            RVhreTdEMTNPWW9qbXF3MmlCalJHRzRPM2s4CjlPeHlvMko3NWYvcENhNGxXNDJT
            TEIxcDVReXBaOGp0TC9kVDdlMFRqTlEKLS0tIG1OMm93eFBNTzF4dFVCTlZhckxN
            bFlCR29WMXJBZFdUcnppcFg5MnNtbHcK1t9uh4xHrWR3BEX/vFRSw8QDBSMsK1ja
            bbLaxenDCVJhaW6VRw5nWsE+BQc6RRBdoPtch9bKTwy1aWkFeJA67g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T03:52:27Z"
    mac: ENC[AES256_GCM,data:SXW3RmY/7G+9DzNxNYbnCkKSAsNYHKzc3pZJHKB5orKIQeyOnxn/s+kxcLSs6X4lflHwi+rmk6mV0/gziFAuX6PRfqIKBMA4BCSWVMHvtgBrQ+BTRarxeM6J9sOnMtg7Ia96Uqkqr0jXyLTMsomAkhjfhGHU5hNViuqCMeJnGPw=,iv:1dGBhiuIs4d9O//PPxtUzXV/KB3DdLqPQU1nzkaVJ1k=,tag:zTxBK3EY86st+WeovYsCQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
