apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:neTIs6F2D1nq7c/7tlHS2BoDDvQUqt+yaeH1YvhjQiE7hYIxO7iBpg==,iv:vTjJ47eyj5rTlJokTKgVL4mB6+2UNvhx5Uvkd36P3eY=,tag:/3GxehLDfTDfml/zKpnJbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHRLTDRLNUwyK1VtUVBF
            dS9OVnNoKytHUVkrWjZRSG1mQWFQS3RiS3ljClZHQXBEbUhaS0dBbjRkdmpzdStm
            ZlhwMXgxOVQ1T0gyUUVUWTFvZGRGNWcKLS0tIHpGSVE3ZzF6UTNOajNxWlhTbmdU
            ZmxreWpMS2RXL2ZhWkxPVXRPMEQ5RTgKXPfG6PrjK3ANlaZB+1QQMPpmPZF/EzRd
            JnAbxL/FKpVrA0RO2aXjulA8VZNR/oP+T+q8+XRHLr0DgLZOj7Sr4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T00:30:31Z"
    mac: ENC[AES256_GCM,data:vxyHDgl/SPVOrcjBpCD2UtY/r3euuJGwgiUmuv3YdStTNZiz6EVFVgeG/sihbCFrz7K1S42tvPs4C3yLxQfb810unlSUdiGmrVWlH6iPBBNnQifu7eVGcVojYpvjN2rVcCH5QGWFeVa0vIFBoMSueQiA21ryVN19/cwcCTUSCPU=,iv:yzDNN/a5TttNcsX3cxPvbyV8Y8cgNC8IqPhsXnDH+6c=,tag:xtX4FzEgTNxKQnHD7fugag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
