apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:G+7k53BSy5xr1mGL2ldGNgF8LSQv3PlWr/D6JIgdAKCsUfpqMge1RQ==,iv:fYTwP/x+crdhFkZR8BBxiqndKQqGyJE9pZOrJjeh/Oo=,tag:S6ViE46BEn7ExFl5CtkhyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a0NpcWVZNVZaT0FRQjd6
            bG5DVnVySFpxNU1IVnN4R2dyUDk5US80clNrCm1pcmtOVWNxYzBNcUpuOThYVmpJ
            b2tOSWE1V2R0eC9oMFhDUUJiSUYwWXMKLS0tIGJIMHZNWHpFNTNwdVE2TW1aYThx
            QXJVcXV3bjN3N0hJaTh1Y2svUXZrUDAKYE2LYvdxeLaUmrSxZ9HCodCBPlpLtJBo
            u0K0LPmK8UlLR44K7FddieifKX1DePGTBFPKvCj5hTeeDZzHW+i5aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T03:28:54Z"
    mac: ENC[AES256_GCM,data:1+HOV7IimDDn2QjwGG3/WeemWpedZ5FFguwdogy2V4Jgff8U3CogpJe0BQRpl0/44QgqvUOGR/6Lq0h7JadLI9nl6tRNXDWm2vFZGN4a8cvGOqRh9a/9DAm/5VFsqynnr8/SoeHSR7BCR0x5dZs1huis8KZ8gI4lSadlZtJOSEA=,iv:/dmtyYKg3fwAxS/c0aaDOIYdBsTGpDFooxNvi6EupCg=,tag:VsyiX5TvQhkBuU9uw2+RpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
