apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:Xb9hoadryHneCUhxZkYJOr1ZOkgS7U6JkvlI2eIEjIWRFMCMCfA2FA==,iv:EevK4aCPQ0hmTTYmeR/xHmk90F+O0BVU2B6Z1C2YvJo=,tag:YHrOn11Jk3Y8cFJBfDmi9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjVjTGJiaU1OMlZLL3U1
            MHFybVpEQU1HcjdwdlFVendINXQ1MEEycFg0CmxXNUdvL25yRGJSaFZKT2x3cTBS
            QTRzTVM1RnNsZjVHaHBLMVF1ZFltRWsKLS0tIFRXRHRscmxpVHREMWlCUDU0YWxR
            SGFwNEdVSVQ4aEQwRjc2U1UzSDd1ZTgKl2HMfOGoi3G1m46WmrXd6w6KtnFcC69J
            m784QCIHSdJB2ni4HN+LYGcxL3iCjq63RaFu7EIng1ALvn39GzuRmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T17:37:46Z"
    mac: ENC[AES256_GCM,data:PYVt5IhiuZIWlFjwj/Waz7ubAKczDQLMyMqEHGswy8muCj1PWcLLk8QFIx7nqeqJphLeDjggTIrXz3siCzfan5ket0HkUyLSADqkj5s8CKqXsiW3NyQ0QpSRT335Wx1UyRzLOQiKDJGFbltnrH80jyX1lipefzpREJDIcS9ouOM=,iv:/R3vlJ3aJEQzXVrTJpRIRuqMRDQwXx6lTS4aySmO024=,tag:8plV9Q8Ee6bh1a6YG1QBmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
