apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:gVvlQmv23M8K4PgqkxV205DBjRue+s24jvN4fb2Be/hbssb4rsKc+l80HqvzFOP5kO6bHXmXd/8v4m/n,iv:bxUcYFjjCDy5Sa6Y1Z1SK7cQTeQGYrVnXRMk2rqSGak=,tag:Oah9Rn59bHqMqyI6bdNjTA==,type:str]
    username: ENC[AES256_GCM,data:VR0Z/gE=,iv:ZvfDngdNhakXbHZi3go+uJ0I4kAK0V9VUZlWPHcEbhg=,tag:+2i9FnWFWwnzu8cr74cNbA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWME5GelE3aGxXUXJ4VTVm
            TkZIQXFxOUdsdVZESnZURUhUL05CKyttMFVVCkdRUUNTbnZKOHU3TnczYXNCSFIr
            M0RuS295bDVpWjErZkl4NFkwSndTMFkKLS0tIE1DRVdvUjlySTNPRXNMQ1NKVUJE
            WlEwcDVTWFFQRmkwaytEd0Nub1ZaQncKIanbiGxt7GZTVhvmK9awas/p0qBdYixK
            MAWv1ZA2k0rPUHyj0hnN+f2IAkqY70w/m/rssMTghp7jDQAz1vsJfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T19:44:29Z"
    mac: ENC[AES256_GCM,data:YLju+eJbHQq7uHhpJ7d1G4gwUB5KD5xFxZoO9SDEf00gSrpOKdsYeyKiGI6oYNVwXsHp5EOgW6eU8SCcF0lrngRC9/NQJYUl4E4TpUc42haq7yNqFvs5QHTCKh02zXeI5FPGdJoggMEZNEWsvypSSuGUzudMscVmJMjPPOseT9M=,iv:JKZHFMhRXR3d7vOci9+c1UrVSVBEYVat77txPtXsbko=,tag:BO5eJJYnnsSQqPr+PE7aSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
