apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:E2PcGdz4JPX2T2V3UruuoqprKq9iBMNlwGyXrobMNPv4tU6oh8sEcjhEGxU4xH3m3PUq9dowZNTf+UnM,iv:lRQu8zuaLP4GdYSO2Hm2JV7sZekhUEU+MXCaT6DxfZs=,tag:dPqdcgmDjFnQz5ooLSN0og==,type:str]
    username: ENC[AES256_GCM,data:hL5kDBE=,iv:goR6eT2Mo+yOnDeH3Gn+d6PAAyaH6Csr9HOy+Ku2otA=,tag:iDOg8PBrt3Va36YX1ivZUg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aHB2RDBLWWp1OFQ4NVVi
            amlzRndkeUVxQ3J4cXkyb2U5UjdzQjU2bkFrCm9PeHJTYWFtSTZYNW8yQzRkREZn
            VmNvUkEzU0tvaDNnRzJEbnNhZlRrNzgKLS0tIGZoNmtFMjdzYzV5SlFpeW9Zc3pt
            WlNiSGlXMXRCckYwNUdaWTBiVnVadGcKkZIz1JYusYcAKA8ys9ygZIsk+PXNw3z5
            6CySaGkdofPC+ihOkCtmTsRL5oR0pF8TvKMF6/rTGqL58DAB6WOx8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T00:30:37Z"
    mac: ENC[AES256_GCM,data:9b50fChf7NHTLQ13ECuvXCqDvKdbra8DKQhSoKBc5GKHV9UuF/EnHi17arRiWdBLqJ26kqzJQwEv4KE1LtgA05sYQjhBU9x2bFec5BBeea6ORERKaXQDoJ5g9b9DuuZ58Afg4r9bzRBYXdDvvINMjub+HJMZoSLm37znF4kIvSw=,iv:8IBlMRloKVQGhEiQ/c8SmbZh655OSg77JebD14GcEEQ=,tag:aw4LfV58L8ZPkgfvQaEtXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
