apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:HPRmc4s6jZk3PxbxWKXQt3Sc2qOkozi2TwIRQN/HlLW7XLwhFSID0Ji5EkFTOLnVpQu9Uzj5eTYh28MY,iv:NoijfrOeepj5KUEo4lTZt0PjKVlXOT1dhL0erw6rxPA=,tag:WzQD6e0VTiYAPebSfY9VRg==,type:str]
    username: ENC[AES256_GCM,data:vmghNj0=,iv:aq2OkDD9f3xD0myYiE7U2hUywsOXXCOlwfUPxnduOBs=,tag:6lXhZmNjCAn5tIDOBxZCUw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4b3VlYk80TTZzdmJ1QUFR
            aU5pSXBkSUJxaGpadW1MVExQQW0vQ09SdHcwCkVCQ0gvT1N6YmY5MXhuTGdLV0xK
            SmNtNkJEUjVPK08vSm9oQ2U5NWlDVDQKLS0tIEJ6NFVwemdISG0wNjRNYkVXbmQx
            SnlxS09RcUhPdmc1bURuSi9CSmYwbHcKVhJ6UbRF69qxg0pHjAJSm741iOBoizca
            SMzNNs5kUAURXxNuDOGMGFS70bRWkF7XZvoMeUQSDfZY4eaRDNOdug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T01:16:02Z"
    mac: ENC[AES256_GCM,data:ZpOuLF3pWQoi6wzSGU1TLWdMFcPbe+/Ab7067rZCe5PLcOKkVJaHqfeKHc78ioWfdo3el5PLyLyYP+6A95n1P/rLMSAw6pZuL4MOYs7GE88FyVGqcjSQ0rWE4+6VqucV6I1GjdC1NKqAL/NWck4JSxywhsg/J02K00tG/nhJnNk=,iv:xDqrd12ugsxyv3k0U5hYIyWzveH1eadEBpwiDg3ff+g=,tag:ithPxPS1A5PABD9r3/aypA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
