apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:Nn74kONv+5qlX2CSTzmJW8EG9xGeekBMdb9SshLtyGZ0CA0UgK6d1kc/xmbfvXVmWEGvE+lLKLPqb/VD,iv:LBr3TyVrkIGFtwh4JO4ysfrvcZiXYaGpt/uFP1KhJtk=,tag:D7aJfXenIHzDk+I0qxNaBA==,type:str]
    username: ENC[AES256_GCM,data:GTUmxRI=,iv:aIpBceYowGRYA9a8X77Rn/7y2+Arw/RDH2ShNF6eh9k=,tag:ye+q7ZTToQyH52sbcLn2sQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOHNiMVVFb0lGdkhrT3JF
            L3pRRFVLTkIrTjZSL0ZDQVFSYy9rU1k1NEJNCklQaDFYNmRyMy8zcTFLZnVpdS9w
            VW5LR2Q3ekFYbHZjTjNtMStQSTlGQjAKLS0tIDBUYkdHWXhINUZva1BDV25IOHNE
            WE9BWlliNlVFV1ZLN0tGRGJ4Tm5Kb3MKAarZs5ZbDJk4IzPJMHvnQvDBf8oVj+bC
            3SSujzRLdKZ063T4GPOkqHTFlrpGayXm5BBNTdc8jSbtIp3XI5jUhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T03:52:33Z"
    mac: ENC[AES256_GCM,data:3X3k31IUqSxVlO7kb6GgZPeZkxei5HMcDDMY0FtO3LELjLqCjshaeiWPPPFqTR716AMXZvLeepbISfQC39BslZeGPUZgQU4GNuKtpLO7rX/NnNSaMBgEI97SAS0Jr1aY2fodRki8HW2I4jjjRyv6MtMu5H6rquRZYxweBfce9ek=,iv:ACeOyqM5aAC/ZHWZ4MiWqg5VOLwzUdNOzA5osAn+ixQ=,tag:hti4HOq7zWGQM9yH6X4Nrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
