apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:FRGjuAQT6Po6WA6OROmf1w2AMCB9pE7JW8vbodyTswc8ipUT0vlYEee8JVgvPpOO/2yRxDDbF8qX4OO0,iv:DbU2QobBjjACErJSbz5dyypu6DvKtFBNBLxSIFxtQU4=,tag:gE2RKi5MI0+iX+CnOtwOig==,type:str]
    username: ENC[AES256_GCM,data:IE32Y7M=,iv:CDrEryoqs4djbQXhrs1woyt4xkx6M5oqzXi6KRUKGPk=,tag:RBMZ0gH82/hvveZatBNDgg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRHRDaXlFL3ZPRWFtRnVY
            RTVndWJiTm16N25Sb1JxYUVVaGFNMzU2aWpNCjRhY3BlOHlCZjZYd25OWVRQTGRV
            NE9NY1N1Znh3eEJrY1oyeFRTemhLVUkKLS0tIExJVlVCUUJSWTRya2hydmdDTVhx
            VzFoYVB5alUvQUF0TytwMGpZWW83WXMKCtD81OcRSJsZP57JQ28dKPf5QnCBI7J+
            2KgKQnACmd31FC2smN5ZMuFqMePHAhy6LhADjp8r/wBwIoWc2nklhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T20:41:26Z"
    mac: ENC[AES256_GCM,data:hC3O4VqMUYb7LpF8Lz22A6uvBJxsollwGZi06gf22dAVbaXYTzPYSI71k9xs7rK4bJw+K9qL+yBHyWlEGZr3kevZiHkVUO2xiuY17mUPrrdYqDXOWVCBXcf/oM3B8fKHT6qhe9GSlZGsGXJYyeUYG3NXS33FfxMsxiwToB5HOpg=,iv:Pclz6Ryw1HyAYWJU+2T0ef6FrioJ9CJFz2Oq9mFvb1o=,tag:HxO5lo0aQrObplBNA3HEIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
