apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:52N6aMNdhjURX/auzxjgcMJNuvamVQlFTSS6cD8cwmL2+1S0,iv:NX88gwS+HXML1LZG+EeNsF9lZMTmarXlP9ghN7g5lU4=,tag:nLXwXQXm2YNFUx2UMSx14A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2dfKs6HrJmnOsEZF,iv:SlOC/WLP5RZDzS/kqILyKkJB8cf4zA1sAvNBgPMkeuE=,tag:m2CxCt0z8g7x/2eKQPPsUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSDNNdU55d0RRcEp6SlFG
            WklOSk5BK1pxWDdsM25abnBad3Vrb2VRTlNnCmNBWmhuNDlqM2RBSGRjS0RiLy9C
            T0wyOGFxQjVVRW1jbHI3aFJYM2JsbUEKLS0tIHV4UjNNemsvOUd5YTVrZzlrR2l5
            enlMVHpTMjdhNENYTW1hbCtVQUxCUVUKMCPAXvnJzxLFNyoBq9xD27Jd88W6erCB
            2teOdNLSRqsy8ju6w7pi3+PmSset/NF0BssQcb2MkEuORrAp8Orkbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T01:15:54Z"
    mac: ENC[AES256_GCM,data:Jbum70fM5NPhoqbRfBr6N5/njHilEXN6JuTFOpwEh26a2GVg40f6ehoR9WAr4p7DNRqwOtIwZpcD2T8PxaaP2crhnF/zVqRIXVdhNgM4cW7uxPtC1fewNxP6SqBhXNsn7rukwC8CcrMe9jxwTnBO3jmcxseXPRseinq2bmY19Lk=,iv:OOiuvefPwNb4pX7rof7CzbXO3uOVY3XFDrm6lMVjYXo=,tag:SuD1to2s6/TRsWH+eyI3AQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
