apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:HGOLCcmPF8tXV+nze1CsFOSHdsT1PLH5R4GJ5eeXZpHuDGXA,iv:LbYhP1vKZn2rqakmBc7XhIPsDgxMzbQ5b+DUHprts60=,tag:zJpOSAGYzSPR+BTVFps1sw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:NclRKGfsZG/OOSTd,iv:sgWyNoFFriLUBU8EFUkYgLweTDmII5twEHQ198uOHXE=,tag:F2kIxrPqt33BtGQ8sO4j5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSVRTdWZ4QnYwVUFIS1F0
            dlY4eXdvSy9SQ3VncXZ3RE41bmUxQXQ3U2xzCkZEYmU1SlBMR1M4SzY5ZmRSWFVp
            MGFuVmxVTlhOYnBpT3ZoaGtQZ29ocXMKLS0tIFVxTjFyWVI3TnFnYkhzWk1PT1VL
            czVGWkVCN3h5TDdjKy9mbEUyWTJXQXcKV4v2/6qKIB+Eh0MchBzWHjhGfGmDLN0n
            CsE1b568f6EaxmUT7SqA2ehln05rX737aFAc1sYqy2Kfgwqlcb6utA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T00:04:18Z"
    mac: ENC[AES256_GCM,data:1dqF16r4AdIZ0Er+0o00iC/mJoZ4gdhNKe4MzcbnY+TfjuM49fno4bPlc/InU4ZCXbo0OcjlPU75Ofl4sCRsn96LUdpDCZ0+qcEQyglfDPfZYp7acaFFB4kdmOibIlPvjbOeVk1xp+mfYPf5XDI3J+mitFybD8AnTiOSLX36rpg=,iv:A65koZNTaRdzlCXpvB5XGSajvRAEIeQ0q3uQbThFqfc=,tag:l9t54Szxf1v+dXbb2gJxZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
