apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:5bQTn1MOo5k2sfgn,iv:Mvl5o8mWZH9q3AvxYiXei6znPzake+2/S1jF44vMQB0=,tag:UMabPxivMgD/XGnf74Falw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2enVnVkwzY1liaHFFYWsw
            UC96ZEZSa0pSLzY5VHBZWkVKbzFpMkx4K1M4Cm5xYlBNUHN0bC9TMGsvNWlsalh4
            a0s4K211d1MyV2pnZ1NRWStMejg5UXcKLS0tIEdTT2E2WE53MWVHZHd1aGszVnU5
            RlR6TzFaZENqWmFYWXVzeUpydnNBSUkKJ36Xwf7RMXnp8nK1QV1x2G6/kn1P1h6O
            PKrv5RxCezp1WUFUY5cyk4IfPuoZMaPkRuoCJ3P1kZASrI4P/nfNmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T22:40:23Z"
    mac: ENC[AES256_GCM,data:XtmuH7s0x9N0UcRyHCF4tFeW1iAJypQzRtbs/He05joYefW0jCL6gxCJqb4YYF1swoYWmMMHTWOGtEydvqKJWncR0DNXwOCR2wS/Aov+ZMj7XiLhq1hr6Ph4bo7tLjh7vs5xi9egODZw0SziLjE7dQZdhuWt1iizQY2vuKHQNhg=,iv:VNYnn3Wy/an7caH+AuFp3QVo406AjMQuTjhXNwwlWhY=,tag:K0eTmBmUFIHUajlx1hoWXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
