apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MeQP9Jq2IsLAR6PysM+RYrOoYI2S2JXxyTYVDN0yrMC0yTkA,iv:spYRZc52gGSA0FXtb7NxvgVoei1Idpt5gZuN41zPwdk=,tag:Bf3o8uuy02gNqQkErs3rDw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:u5C4//bn5FdLCLDC,iv:nlDdMw9I9f0vlKg5mdfNm/5rsvEuPqas2h2bhWS1WcI=,tag:b5pX4iT/2oRc02jjDKQxQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNCtZWGlvVVE1V1BzK0d4
            YjY0N0FBTVgzT0RwdFJLVW8vWkJaVFpJRFhJCjRMTHBPTnBLRWpzNysvNGhNaGUr
            UENBSitiVGdmbkpUY3FUM29saFVrMHcKLS0tIG03eXVxTzVFNFl2bnRjVzBEQ1Ri
            UklFM3hQcGI0SzlvbHVhN0NJblo3SmsKN6IbRjH7z2a/J4kNIftK/Si1gYZiLAyb
            0V1Otle356mlnFLuCVSxsjF5hG8klz5WU4W9l4o7B6ezHrnQWvSkfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T00:30:31Z"
    mac: ENC[AES256_GCM,data:xYaPv+Yact4e1pZrXbvTMpkSdrHxJUinmdPXfxiQk15VUM/AWn2AP3HM0ofZuXFGGLM0i9hCkiQzfg/8UB1gO9hJ2tkdqQSbnDKCJgS4sxtYT5uc5u9gtvwN+0SfkMUPsa0mFazhtxN/RB6lw7HPNU+ccvgdP/bFlScEXhUFSPo=,iv:Nya+PWqWhKhr0T4uFzRbgYgR8b15dUB4kRpEro4sWok=,tag:b9/FZu5oHqYG7Cp6DhIpLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
