apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:uVuLzv145CvQpk4U,iv:xJq4anfyFzz5iTIwP5D6D5IL6xi9+wpxYIC/5uqZDcs=,tag:bBVEO2Rg2BfnXPnjegWjzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORExiQXduR3RocFQ4NnZ1
            Zm1zMWgwZDRCNkNLeFNjdDFrUG9ITzVXTUZFCkxNZ0x1cmFENnVEWkRLL0xKSm14
            VlMxVVpNeTNZTzVpSFdvUHBqWjF1aG8KLS0tIG83WW9VdG96ZjQ1bnIraFM2OWVh
            OG9TcytTQmR4d1lKUWE3VVFHQngybVkKUfO0RQ6KKtzNZRajd5hZ4uN3hloh5vyX
            FzmBTBkTSiXQM0y5/t05ClQSm+OCFi+cTpQCIIqsomqYvaaPOOK/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T00:04:18Z"
    mac: ENC[AES256_GCM,data:zkoiqUngaFSPvQat8oI8U0wtUaDJ62T+SDJoGf8Z2UdyTsZ9YPKdshChuLOdNPTcjzmU+L/kU6dRUFKOg8wOTMja7EkAQ6lGO/NviPNO3xvg/BxxTNk4hYDsn1ZUnR7h/roDEYZ8d41CdZU407bvybkg4QBlbWAHUmHDKOsHmPs=,iv:L9yW6EUT6s4RhdS0ZTtBOd4nQTQEgZJmhyxf2FsjVhM=,tag:LNW5RP4wSr3os0tNG/8X7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
