apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:/05swDzeKzBEqtRG,iv:sL3cHLbs8PvDv7HJWljjV3YUeKpJ7VL/AfS6rSauAR0=,tag:Z3+7DLUWXZvyfCZeMPvoiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VDRDQjZxWkhuNis1eXR6
            eXBxRnBTZVBuRFRXbEM0U01UTWY3M2oxd1VVCnJ0WVBNSlZXVXFjc25ZVWtORGtN
            MEV4OXpGSUVqU1JTbGdzTGxRclIvclUKLS0tIEVhTTdNQmJEUEh2c1puc1RFcFhW
            RGhva0R0cjRVTllwZGJmSVNRTlR1Sk0Kc5CY+mJK2OdLzRkL0cJBeiSgx9ciK9LK
            mm7fbVBleHPZjZgshk0lOqbCKp+zUwOguYzh/mvhHhiS88s89Kgr9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-26T23:17:51Z"
    mac: ENC[AES256_GCM,data:qbgt79tPYRoS1OnfAIf0zZxL7SimwpmhD5smZem5Vvji7TQnZXfHbW9LY2TaHM8P0XAaQxgygVg7aLX87C/lEqCv3jOVFgf0QyDsG7uO4PjmKlsuWnbr5ROeDRAINbziCFMd1b5M8otSwHXNUYN7F5Z4j0nmwcI1Yt8SQ21Q3L0=,iv:U5sEaSHs/qi3sCX18FAYRuNvSFpyDUEA9h/EcMguQ8U=,tag:np6epqhF/bhTiPT2WQ2ljg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
