apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30s
  chart:
    spec:
      chart: plex
      version: 7.1.4
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  maxHistory: 5
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: kube-system
  values:
    env:
      PLEX_CLAIM: claim-LxCoz5g7xD5u_xipscFu
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: plex-config-pvc
        retain: true
      transcode:
        enabled: true
        mountPath: /config
        existingClaim: plex-transcode-pvc
        retain: true
      data:
        enabled: true
        existingClaim: media-pvc
        retain: true
    ingress:
      main:
        enabled: "true"
        ingressClassName: internal
        annotations:
          "plex.io/enable": "true"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

