apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30s
  chart:
    spec:
      chart: plex-media-server
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  maxHistory: 5
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: kube-system
  values:
    extraEnv:
      PLEX_CLAIM: "claim-SyaHPTiuJxxPt1tEttHh"
      HOSTNAME: "plex.casazza.info"
      TZ: "Etc/UTC"
      PLEX_UPDATE_CHANNEL: "5"
    nodeSelector:
      kubernetes.io/hostname: "rog"

    ingress:
      # Specify if an ingress resource for the pms server should be created or not
      enabled: true

      # The ingress class that should be used
      ingressClassName: &host "plex.${SECRET_DOMAIN}"

      # The url to use for the ingress reverse proxy to point at this pms instance
      url: *host

      # Custom annotations to put on the ingress resource
      # annotations: {}

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: plex-media-config
      transcode:
        enabled: true
        mountPath: /transcode
      data:
        enabled: true
        existingClaim: media-pvc

    # ingress:
    #     enabled: "true"
    #     ingressClassName: internal
    #     annotations:
    #       "plex.io/enable": "true"
    #     hosts:
    #       - host: &host "plex.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - *host
    #   main:
    #     enabled: "true"
    #     ingressClassName: internal
    #     annotations:
    #       "plex.io/enable": "true"
    #     hosts:
    #       - host: &host "plex.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - *host

