apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: plex
      version: 7.1.4
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  maxHistory: 5
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: default
  values:
    env:
      # ADVERTISE_IP:
      # ALLOWED_NETWORKS:
      # PLEX_CLAIM:
      PLEX_PREFERENCE_1: "FriendlyName=plex-kubernetes"
      PLEX_PREFERENCE_2: "EnableIPv6=0"
      PLEX_PREFERENCE_3: "logDebug=0"
      PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
      PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
      PLEX_PREFERENCE_6: "TranscoderQuality=2"
      PLEX_PREFERENCE_7: "TreatWanIpAsLocal=0"
      PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=fast"
      PLEX_CLAIM: claim-kSmGk1N8SxsyARJ6fp48
    persistence:
      config:
        enabled: false
      data:
        enabled: true
        existingClaim: longhorn-media-pvc
    ingress:
      main:
        enabled: "true"
        ingressClassName: internal
        annotations:
          "plex.io/enable": "true"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

