apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
spec:
  interval: 30s
  chart:
    spec:
      chart: plex
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: flux-system
  maxHistory: 5
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    nodeSelector:
      kubernetes.io/hostname: rog
    persistence:
      config:
        enabled: false
      data:
        enabled: true
        existingClaim: "media-nfs-pvc"
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        plex.io/enable: "true"
      hosts:
        - host: &host "plex.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

