apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: default
spec:
  interval: 30s
  chart:
    spec:
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 5
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
  - name: cluster-apps-nginx-internal
    namespace: networking
  values:
    persistence:
      defaultNodeSelector:
        enable: true
        selector:
          nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - rog
                - jensen
    ingress:
      host: &host "longhorn.${SECRET_DOMAIN}"
      enabled: true
      ingressClassName: internal
      annotations:
        longhorn.io/enable: "true"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

