apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6Hi4msXCWz1QzMPAmRPivWpdS1Xq7fqQhfbyPLZBaSX8quus,iv:x6B+o8oQec8HLiZ8BHPp7OZhOO0BE7DU0mZ0pjqIDfs=,tag:F/CXYmTlgvJM1zFOgMudFg==,type:str]
    credentials.json: ENC[AES256_GCM,data:5gt/3m17kRKqPUVvHaSCE0fw2h2r/PT4FIZKpBCSZTLDWYoUwTV/4fgmOulJ8hYVj9uF+LMKtY7QB10qy6stTzGx22Via/+1i02ZBZBZPNzCXBOVYaCDNVFMBFB+H4lNL3Z+16El4u/gJzaS5QfAKnIMD8rAG1Y+BhquRNp1vuZv9wYFcp5ZOG55su1NpKEfJlGTFIBSvNB8dIdeKhhSoQ40r9I1cyEk91gvRs1iKg==,iv:pv/Zm5fjMQfl0vU1ZntSIJWtYACENMFrnKQmFjQsFIk=,tag:OJbzqDXBGXRbMHRwgJ/5zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZEtaN0JhQUl0Qm5WWCsz
            UHJlbHR4YWxYampzYVlYRUZmKzAxVVIyeEVFCkxzZ3EwUDNJZmNGMXVmdHRqQ0FC
            VlVMTUQ0NnByOHRjSmtkZ1hsWmlxSVUKLS0tIEhvMmlBVSs1UFd4eXlhdENKVWRa
            WmlhU3pxa0lJMkQ1Y2YyNGxzVkF2TXcKpC5q12kZ5hH+BmaPaxYSxuS+GE39RSp7
            vL9CLSAy7oICjpz9Eimy1YAH9pYdn5Pkr3VsFeZmP8nOHDs0v699FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T17:37:46Z"
    mac: ENC[AES256_GCM,data:qxwAJ3Q5mlUhxauySi1RbfnyMb8FLGB6F0uvALrxpf/uLwk6zaaSToYEzekIRI5gynxUGZEvl1jZeIls0PJVcRROkeCsP6ExlvL/3t95hDMbnB8NCPRzDZB2AFGXGiQNVa6HB9N9YTFI0uJRGLG9xeL/e64P4cXsOIyenbSENsA=,iv:+prdDtThl6e/CE1AhNfJQMBQ70P1V3XFlxrxBVIq8U0=,tag:buIyUYtPem/pz83z4thxbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
