apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:of9h2E/0M3+yGf3PgpCDgp0Hso7HR2xxbP5KP+0H2z4GvLtt,iv:xIg9Jw96lTmo8C2hLeUwGRDqAGXaSWKR1GWa/BNlfEs=,tag:ItpLGuZAlKDsdDjNX4gPYQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:RwSojg70NS6B/VuTvrwd/YNPJBaqIa0FU/BfOZLalnsVr7AG85CeKZbClFp9Ctbv2i6REh+wGmnij4TNcQQACQaMpxBG7fVf9jhS60FXQZWCUvsK7CHz7Ws6d2TsSxg5VWJFCMs4Uc96QMDFqrEhcHFcfSmdmAkITDYIAqfB7Y5yKhg8IdyGkudZxqw1Wd6UPmA6Fg6gM+yRE3ip0uJ+qxIjxRMVuwz5sCzERtuD5A==,iv:fHDfV6vAifq6r7i7zFlXxdYStjys1BAN6nDPeGGZLgA=,tag:KFMNZVY/5swcihFtjKSy4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSXZQNnZ4M1UzVzNpUFRB
            MnIvMVc3NTJZTGJXT2d5Y2ZDOXcxWDdONXdzClJibXMyYjVMTXZTRlRyMzcwdjBL
            ZVBXTytUenMvRXIzTXlzOTlSUDhhN3cKLS0tIG1oMkZDWXJKR0IydEdVSmdDTVd3
            c1ZTZDVFcGJHMGJ6MTA3amZsYy91Y2MKMs3nS5jeHBEab/w8X2xEUrqcy+pLcU9t
            v/vWVTmoMbHkOr+kO4UGjL5utiEDvuK/XD9SL/5fFrsb5Ft7K9kCxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T22:40:24Z"
    mac: ENC[AES256_GCM,data:KSNUC9FJE+0gj8AGzD7f8HIoD9aMcqnd7HQfUhyp6utHuB5XeaL2j2O7ZcJyiSkFBxZdQ+xHCtzmZaF+F2AzYBuLSTskHmKsHCwTst5oK5YWgdGoErNPWvF1xx7VNsW70ZPN4ZQom4O4Pp5ITUd1RLX+ekE0JUl7wJc6vzTa7Mc=,iv:f4UqrU0amTXO7Dj7+M2Pu8hjjo+BFLZtrCBggvXjjjQ=,tag:akBeLDul/zATpzfKvCePvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
