apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ebTO7e7EJYJ4l4ShCGf2oU6BWthk3VRx7VXrWdU1AT7IE5z2,iv:DqQ23RAPuRdHPFrnwWzM44awhjUaoFxlKOhzxClqR1A=,tag:wzqIgnnm8bagNFi9NprCoA==,type:str]
    credentials.json: ENC[AES256_GCM,data:PYUiTtGmZNb5jDTzJxslz6aBWt9jgzVoxwAYeLiEPwTlxI9dMzuhG96zpfgv4VfdFV8aP+UqZc8I5TO/+KRp8VpJz8sjBlHsAmKKVKBGedLblUUCT1r/X1uNDlrtd/Kh4WAWdSu81Qj5SktDj20dEOkN8TkB08PwgGk9kUEAvouFQNxfOignmVHCHQu5Nvit1Has6JHo8cJ3h/XUx244U/0uqdtijjI6uPhThYMW7w==,iv:DXC+YXTJJxv91m5KR5eibcSz4MQjzS8dbb6M8DyHPVk=,tag:UMCXhWt6ggLHYrrtZnSXiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeHkzVytsa3BIYU1oSlYv
            dmFzVThFclJzSDg2ZGNPSG5zYUpydEhsQmtvCjR2Qm44UVFUeVo4N2RrN1NUTTk0
            WFhLYVZ3cllTVDBZVWcwSnhCcUUvbEEKLS0tIDNCY2NDSUNock8yWWRRWTBkVHZi
            bjFDc2Jva2l5dXhLZmpRVmxJemx6N3MKG/+5l/1S3JTB/hPMF4W/G2qrY9p+cT/4
            wjb6KkFfW7gW9uiFw/i6nnrfRIhOBjxfXjyD57C/N4eiHbdUvOBM6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-25T01:52:20Z"
    mac: ENC[AES256_GCM,data:noyLOndebn7o0pFCyf+E2ETHgDwX4cqqsafSrwHrDfj50WMV26Fc0YoOt7i9kYJpZCMXYuZ5wHs0I3pDwqNgXS0ywF1LDCZSv2LarDet6ImFOnv/RwHvMpaaFCKEOeGAeB0uaIT5euo/15vX42KOsED//NUiBtxuF2JUtK8WQg8=,iv:cNGvoUwpslkwt01m6qCkU6GKp73uxysDiYVGYIpogL4=,tag:JTsYRSn30j4HjyIedwrH4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
