apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2nMN95SxHjome8x9bwxmGjYNO6QU4nZS6vrMjT9vJEfZad8n,iv:pd0jiUk91zmep+NOyf3rSlXuyD1+iRaxIl1zdvW3+Ko=,tag:xonq7iWAJTZQCcOOmEzmDg==,type:str]
    credentials.json: ENC[AES256_GCM,data:ILp3cbpbaQZEE6dWZ35/jXCPqzu0PUuI0v2uN/yyndzfm95JZpLmgViZ8jGsyMdUcs5OoyXgMABxlLRyhWadQ/K5DBB20uy3exVB94tTd+7DcfQ3QatfMslDovA0TMdWgswNb6qRZ4O2quGipo1oodYi+ZH/fCvnXbRCILUNKmAZzqsN0hLK7b+OZx3bCKVAuNKQQk6BIwXzzJGOcBbbqhiT+XXfYr8wVIpSMP/VVw==,iv:9YsH3RpK7ZbGKKolq8DS9PgbAfCBLk8fzjJ2gzUD6GE=,tag:GrpRsZTRiKdjfFuEhfDZcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZ2dtdmhYdWFVSHFWeWdj
            MVNETjUyeTdtaGlKQlhwS1F0eENUT1Z5UVIwCnNMeHg0a3FuUit0U3lkWVE2eld4
            M3pxOHhZYW1BZGNraGNZbTBYM1d3blEKLS0tIFppUy96YkliWXFZSEhvYTFPcjkw
            dzJOeHorNGE0US9paFhzL251TGViMHMKPj0c1uKmb8Jp7ridFI3YsG9EfAB+86CK
            FOWDeHSWO3nbUkqHvtOR1jy3xvFR6XlyJ2B7fD/UFySk984K6xd4Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T19:44:21Z"
    mac: ENC[AES256_GCM,data:uNtGgm6Azh74e+Zx/1lGRVGOy6Q66s63VvxDn6inwSPgm/H3DKBbDZtSgWlF/QL42ys/0s/Is0SagGbSeFPs1kVGAhMLIK1fcHYogj9+Kc1neFO+hJ64CfWkkptij6jN2peUtcOUNjzeWDTZ4LkqfAy8/8osiH2aQBOKg21AM2g=,iv:6FE6mL28GJMenhrWMKq6eS+aCh4wbFodw9/jiqTIYME=,tag:rUwaUuRGldYDNdBgpKs0oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
