apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Io+LhT8d2GSjC1dTfPTrwONUxI6EGlPt80GbAt2tbwBR8l/2,iv:HRixjEYtf1WcEtjnVDMRVyFph8yx7z+hMVKxhczcpEA=,tag:way4zl1K732jldmTDaAWfg==,type:str]
    credentials.json: ENC[AES256_GCM,data:Mzu1sdXnkAZO82pE4qTWp+CPNx3xRrNEETInNTmmL6snWseeBdxCsKZzGJj1RxRbZXaQFlrC2dxslKWL3VLThFnWA7Ub/etLiOzLkAjIIUTLpSPwRowNSfwOBsoXE0Df7TViRJyaHVoF8SZMxGeK1fA37obCJTuaEpdnQQDnDxAL2RPEFWxW73gHVX4axKxFpxVdSBZgxib8EV9JfKuWxICLdihLDMwSS9vQcYdkhw==,iv:SWMR2Kfpi/WQhqpf/xdoz3JAvyJlWir7CKYOZDxbOxc=,tag:Aq9apHR4/Kp6CBCpN6ApHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10nm67xhzd7mm2l47084vsc2wjrlcudg9rrvq8zc6tafwk33k6y7spdncdu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cmRMeHNPbkNzd2hlYVlJ
            ejdzK1MvNG44QlAwYU9ENXhJamFqSytzZVQwCkRyV3JLMkNkbGZpeEhua1ZUcFg5
            cWlJdXgxVm1QUjhHcWM1My82TExGcEEKLS0tIFk0bGlMWTZ6M0ttSlB3eFdOdjQ0
            TmI1TTVTOHlsbVVOZVNueTZYRno1S0EKX3BgJP5wWIUIV2rX2UD5qSkH3pKyz8kq
            m08/L2/be75e6ijo8NPI9V97MKUQ73mXKO6k7KN56Ow2oOZeTCa2Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-29T03:36:41Z"
    mac: ENC[AES256_GCM,data:Jc4H6wugyBarLmnAYFlv9zI+P33aIAnKtU9QU9CGimIIEIF5lIIBfqIuI48tlb4de01wjqTS54LDkn6KREr7h0mixRm1FjN6uVvsFp94beHEaV04XionLQDJ7vJwejChynZtDV6nXjCsHolpe2K1Szx30Av165iR43D7oiRe+uM=,iv:ajtxhV1fXx3hlZQUTdOJBZjs8SG5zKwDQpYQEv2eEaE=,tag:2u9Pk7ZXAoh76IovASbGMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
