---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bittorent
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: bittorent
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: bittorent
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          bittorent.io/enable: "false"
        hosts:
          - host: &host "bittorent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
